-- script that create all the tables we need in this app

-- first we create the tables that doesn't have a foreign key

CREATE TABLE role
(
    ROL_ID_ROL_PK INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ROL_NAME_ROL VARCHAR(20) NOT NULL
);

CREATE TABLE category
(
    CAT_ID_CAT_PK INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CAT_NAME_CAT VARCHAR(255) NOT NULL
);

-- then the ones that have a foreign key

CREATE TABLE user
(
    USR_ID_USR_PK INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USR_LOGIN_USR VARCHAR(100) NOT NULL,
    USR_GENDER_USR VARCHAR(100),
    USR_FIRSTNAME_USR VARCHAR(255) NOT NULL,
    USR_LASTNAME_USR VARCHAR (255) NOT NULL,
    USR_EMAIL_USR VARCHAR(255) NOT NULL,
    USR_PASSWORD_USR VARCHAR(255) NOT NULL,
    USR_PHONENUMBER_USR INT NOT NULL,
    USR_ADDRESS_USR VARCHAR(255) NOT NULL,
    USR_ZIPCODE_USR INT NOT NULL,
    USR_CITY_USR VARCHAR(255) NOT NULL,
	USR_ROLE_ROL_FK INT NOT NULL,
    USR_SIGNINDATE_USR DATE NOT NULL,
    FOREIGN KEY (USR_ROLE_ROL_FK) REFERENCES role (ROL_ID_ROL_PK)
);

CREATE TABLE booking
(
    BKG_ID_BKG_PK INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    BKG_IDUSER_USR_FK INT NOT NULL,
    BKG_ID_PRODUCT_PRO_FK INT NOT NULL,
    BKG_PICKUPDATE_BKG DATE NOT NULL,
    BKG_DROPOFFDATE_BKG DATE NOT NULL,
    BGK_SUM_BKG INT NOT NULL,
    BKG_MESSAGE_BKG VARCHAR(255),
    BKG_RESPONSE_BKG VARCHAR(255),
    BKG_ISCLIENTREACHED_BKG BOOL NOT NULL,
    BKG_STATUS_BKG VARCHAR(255) NOT NULL,
    -- dans l'API ce sera probablement un enum
    BKG_ISPROCESSED_BKG BOOL NOT NULL,
    FOREIGN KEY (BKG_IDUSER_USR_FK) REFERENCES user (USR_ID_USR_PK)
);

CREATE TABLE product
(
    PRO_ID_PRO_PK INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PRO_NAME_PRO VARCHAR(255) NOT NULL,
    PRO_DESC_PRO VARCHAR(255),
    PRO_PICTURES_PRO VARCHAR(255) NOT NULL,
    PRO_RATE_PRO INT NOT NULL,
    PRO_INSTRUCTIONS_PRO VARCHAR(255),
    PRO_BOOKING_BKG_FK INT,
    FOREIGN KEY (PRO_BOOKING_BKG_FK) REFERENCES booking (BKG_ID_BKG_PK)
);

CREATE TABLE categories_products
(
    CPR_ID_PRO_FK INT NOT NULL AUTO_INCREMENT,
    CPR_ID_CAT_FK INT NOT NULL,
    FOREIGN KEY (CPR_ID_PRO_FK) REFERENCES product (PRO_ID_PRO_PK),
    FOREIGN KEY (CPR_ID_CAT_FK) REFERENCES category (CAT_ID_CAT_PK)
);

CREATE TABLE review
(
    REV_ID_REV_PK INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    REV_IDBOOKING_BKG_FK INT NOT NULL,
    REV_CONTENT_REV VARCHAR(255),
    REV_MARK_REV INT,
    REV_VERIFIED_REV BOOL NOT NULL,
    FOREIGN KEY (REV_IDBOOKING_BKG_FK) REFERENCES booking (BKG_ID_BKG_PK)
);